title: Jahongir Qurbonov
description: JSON ga o'xshash microtheme
url: https://jahongir-qurbonov.github.io

theme: null

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  